# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.0'

target 'cocoacicd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.0'

  # Pods for cocoacicd

  target 'cocoacicdTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
